[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.4", features = ["json"]}
tokio = {version = "1.37.0", features = ["full"]}
scraper = "0.19.0"
json = "0.12.4"

